/*
    Author: David Castrillón
    Date: 2023
*/

/*
    -- UUID DATA TYPE

    - UUID stands for Universal Unique Identifier defined by RFC 4122 and other related standards. A UUID value is
        128-bit quantity generated by an algorithm that make it unique in the known universe using the same algorithm
    - Because of its uniqueness feature, you often found UUID in the distributed systems because it guarantees a better
        uniqueness than the SERIAL data type which generates only unique values within a single database.
    - PostgreSQL allows you store and compare UUID values. It relies on the third-party modules that provide specific
        algorithms to generate UUIDs. For example the uuid-ossp module provides some handy functions that implement
        standard algorithms for generating UUIDs.
    - PostgresSQL also provides the function gen_random_uuid() at its core
*/

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- To generate the UUID values based on the combination of computer’s MAC address, current timestamp, and a random
-- value, you use the uuid_generate_v1() function:
SELECT uuid_generate_v1();

-- If you want to generate a UUID value solely based on random numbers, you can use the uuid_generate_v4() function.
SELECT uuid_generate_v4();

-- Creating a table with UUID column
CREATE TABLE contacts (
    contact_id uuid DEFAULT uuid_generate_v4 (),
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    phone VARCHAR,
    PRIMARY KEY (contact_id)
);

INSERT INTO contacts (
    first_name,
    last_name,
    email,
    phone
)
VALUES
    (
        'John',
        'Smith',
        'john.smith@example.com',
        '408-237-2345'
    ),
    (
        'Jane',
        'Smith',
        'jane.smith@example.com',
        '408-237-2344'
    ),
    (
        'Alex',
        'Smith',
        'alex.smith@example.com',
        '408-237-2343'
    );

SELECT
    *
FROM
    contacts;

-- USING gen_random_uuid()
SELECT gen_random_uuid();

-- CLEANUP TABLE
DROP TABLE contacts;
